upstream auth_service {
    server auth-service:8000;
}

upstream medication_service {
    server medication-service:8000;
}

upstream event_service {
    server event-service:8000;
}

server {
    listen 80;
    server_name _;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location = / {
        default_type application/json;
        return 200 '{"name":"MediBox Cloud Gateway","status":"ok"}';
    }

    location = /health {
        default_type application/json;
        return 200 '{"service":"nginx-gateway","status":"ok"}';
    }

    location = /auth {
        return 302 /auth/docs;
    }

    location /auth/ {
        proxy_pass http://auth_service;
    }

    location ~ ^/patients/[^/]+/adherence-summary$ {
        proxy_pass http://event_service;
    }

    location /patients {
        proxy_pass http://medication_service;
    }

    location /medications {
        proxy_pass http://medication_service;
    }

    location /schedules {
        proxy_pass http://medication_service;
    }

    location /events {
        proxy_pass http://event_service;
    }
}
