apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: medibox
spec:
  selector:
    app: nginx-gateway
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
