apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-worker
  namespace: medibox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-worker
  template:
    metadata:
      labels:
        app: notification-worker
    spec:
      containers:
        - name: notification-worker
          image: medibox/notification-worker:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: medibox-config
            - secretRef:
                name: medibox-secret
