apiVersion: v1
kind: Secret
metadata:
  name: medibox-secret
  namespace: medibox
type: Opaque
stringData:
  POSTGRES_PASSWORD: medibox
  JWT_SECRET_KEY: change-me-in-production
  RABBITMQ_DEFAULT_USER: medibox
  RABBITMQ_DEFAULT_PASS: medibox
  DATABASE_URL: postgresql+psycopg2://medibox:medibox@postgres-service:5432/medibox_cloud
  RABBITMQ_URL: amqp://medibox:medibox@rabbitmq-service:5672/
